name: DorisPlugin
version: '1.0-SNAPSHOT'
main: org.exam.dorisPlugin.Main
api-version: '1.21'
commands:
  도:
    description: 아이템 옵션을 설정합니다
    usage: /도
  bos:
    description: 엔티티 설정
    usage: /bos